version: 0.1
actions:
  definitions:
    - id: go-mod-tidy
      display_name: Go Mod Tidy
      description: Runs go mod tidy when changes are detected to go.mod.
      run: ./go-mod-tidy-vendor.sh
      import_to_global: true
      triggers:
        - files: [go.mod]
