version: 0.1
actions:
  definitions:
    - id: go-mod-tidy
      display_name: Go Mod Tidy
      description: Runs go mod tidy when changes are detected to go.mod.
      runtime: go
      run: ${plugin}/actions/go-mod-tidy/go-mod-tidy.sh
      triggers:
        - files: [go.mod]
